# Generated by Django 5.2.3 on 2025-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_notification_token',
            field=models.CharField(blank=True, help_text='Token for push notifications', max_length=255, null=True),
        ),
    ]
