# Generated by Django 5.2.3 on 2025-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_push_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_language',
            field=models.CharField(blank=True, help_text='Main language of the user, used for transcription and captioning', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_language',
            field=models.CharField(blank=True, help_text='Secondary language of the user, used for transcription and captioning', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER', 'Supervisor'), ('STAFF', 'Staff')], default='STAFF', help_text='Type of user for role-based access control', max_length=10),
        ),
    ]
