# Generated by Django 5.2.3 on 2025-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorawupload',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='extracted_audio/'),
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='audio_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
