# Generated by Django 5.2.3 on 2025-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0002_videorawupload_audio_videorawupload_audio_extracted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorawupload',
            name='audio_extracted',
        ),
        migrations.RemoveField(
            model_name='videorawupload',
            name='extraction_error',
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
