# Generated by Django 5.2.3 on 2025-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0003_remove_videorawupload_audio_extracted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorawupload',
            name='audio_extraction_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
