# Generated by Django 5.2.3 on 2025-06-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0004_videorawupload_audio_extraction_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorawupload',
            name='audio_transcription_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorawupload',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
