# Generated by Django 5.2.3 on 2025-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0005_videorawupload_audio_transcription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorawupload',
            name='vtt_file',
            field=models.FileField(blank=True, help_text='WebVTT file for the transcription', null=True, upload_to='captions/'),
        ),
    ]
