# Generated by Django 5.2.3 on 2025-07-01 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_management', '0006_videorawupload_vtt_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for the task completion', null=True)),
                ('taskee', models.ForeignKey(help_text='User who is responsible for completing the task', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('tasker', models.ForeignKey(help_text='User who is assigned to the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(help_text='Video associated with the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='video_management.videorawupload')),
            ],
        ),
    ]
